apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2pzaW5naGcuamZyb2cuaW8iOnsidXNlcm5hbWUiOiJkb2NrZXItamZyb2ciLCJwYXNzd29yZCI6IjIyMzAxOTI3MjVAUG1qc3AiLCJlbWFpbCI6Imphbm1lamFpc2luZ2hnQGdtYWlsLmNvbSIsImF1dGgiOiJaRzlqYTJWeUxXcG1jbTluT2pJeU16QXhPVEkzTWpWQVVHMXFjM0E9In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2023-02-19T17:58:05Z"
  name: mycred
  namespace: ttrends-ns
  resourceVersion: "13184"
  uid: a8c0bf85-4576-4ddd-81c3-3a63889047c3
type: kubernetes.io/dockerconfigjson